import Link from "next/link";

export default function Footer() {
  return (
    <footer>
      <div className="frow">
        <div>
          <div className="logo" style={{ display: "flex", alignItems: "center" }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              alt="OpusSignals.com"
              style={{ width: "150px", display: "block" }}
              src="/OpusSignalLogo.png"
            />
          </div>
          <div className="ftagline">Less Noise. More Conviction.</div>
        </div>
        <div className="fdisc">
          The stock picks provided on OpusSignals.com are generated by the
          proprietary{" "}
          <span style={{ textTransform: "none" }}>
            OpusEngine
            <sup
              style={{
                fontSize: "60%",
                fontWeight: 300,
                verticalAlign: "super",
                lineHeight: 0,
              }}
            >
              &trade;
            </sup>
          </span>{" "}
          methodology and are for informational purposes only. Nothing on this
          site constitutes financial advice, investment advice, trading advice,
          or a recommendation to buy or sell any security. Past signal
          performance does not guarantee future results. The number of picks
          issued per week will vary based on market conditions and conviction
          levels &mdash; no minimum number of weekly picks is guaranteed except
          as stated in our subscriber terms. Always conduct your own research and
          consult a qualified financial professional before making any investment
          decision.
        </div>
      </div>
      <div className="fbot">
        <div className="fcopy">
          &copy; 2026 OpusSignals.com &middot; PnFChart.com, Inc. All rights
          reserved.
        </div>
        <div className="fshare">
          <a
            href="https://twitter.com/intent/tweet?text=OpusSignals%20will%20give%20you%20an%20Unfair%20Advantage%20in%20the%20Stock%20Market.&url=https%3A%2F%2Fapp.opussignals.com%2F"
            target="_blank"
            rel="noopener"
            aria-label="Share on X"
          >
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
            </svg>
          </a>
          <a
            href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fapp.opussignals.com%2F"
            target="_blank"
            rel="noopener"
            aria-label="Share on LinkedIn"
          >
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 1 1 0-4.124 2.062 2.062 0 0 1 0 4.124zM7.114 20.452H3.558V9h3.556v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
            </svg>
          </a>
        </div>
        <div className="flinks">
          <a href="https://www.karimpirani.com" target="_blank" rel="noopener">
            Karim Pirani
          </a>
          <a href="https://chart.opussignals.com" target="_blank" rel="noopener">
            P&amp;F Chart
          </a>
          <a
            href="https://www.investorchatter.com"
            target="_blank"
            rel="noopener"
          >
            InvestorChatter
          </a>
          <a href="https://www.ibbq.com" target="_blank" rel="noopener">
            iBBQ
          </a>
          <a href="#">Privacy Policy</a>
          <a href="#">Terms of Service</a>
          <a href="#">Disclaimer</a>
          <Link href="/contact">Contact</Link>
        </div>
      </div>
    </footer>
  );
}
